package vista;



import java.util.List;
import javax.swing.JOptionPane;
import logica.usuarioLog;
import modelo.Usuario;

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {
    
    private usuarioLog usuLog = new usuarioLog();
    private List<Usuario> ListUsuarios;
    public int userLogin;
    /**
     * Creates new form Login
     */
    public Login() {
        super("Login ASISEVALORA S.A.");
        userLogin = 0;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ingresarL = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        userText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASISEVALORA S.A.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Usuario:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Contraseña:");

        ingresarL.setText("Ingresar");
        ingresarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarLActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(ingresarL)
                        .addGap(97, 97, 97)
                        .addComponent(salir)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresarL)
                    .addComponent(salir))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarLActionPerformed
        ListUsuarios = usuLog.consultar();
        boolean ingresarBool = true;
        for(Usuario u: ListUsuarios){
            if(userText.getText().equals(u.getCedula()) && passwordText.getText().equals(u.getPassword())){
                if(u.getTipoArea().equals("Administrador")){
                    Admin ad = new Admin();
                    ad.setVisible(true);
                    ingresarBool = false;
                    dispose();
                }
                else if(u.getTipoArea().equals("Financiero")){
                    userLogin = u.getCodigo();
                    BSC bsc1 = new BSC(userLogin);
                    bsc1.setVisible(true);
                    ingresarBool = false;
                    dispose();
                }
                else if(u.getTipoArea().equals("Cliente")){
                    userLogin = u.getCodigo();
                    BSC bsc2 = new BSC(userLogin);
                    bsc2.setVisible(true);
                    ingresarBool = false;
                    dispose();
                }
                else if(u.getTipoArea().equals("Aprendizaje y Crecimiento")){
                    userLogin = u.getCodigo();
                    BSC bsc3 = new BSC(userLogin);
                    bsc3.setVisible(true);
                    dispose();
                }
                else if(u.getTipoArea().equals("Procesos Internos")){
                    userLogin = u.getCodigo();
                    BSC bsc4 = new BSC(userLogin);
                    bsc4.setVisible(true);
                    ingresarBool = false;
                    dispose();
                }
            }
            else if(userText.getText().equals(Integer.toString(u.getCodigo())) && passwordText.getText().equals(u.getPassword())){
                if(u.getTipoArea().equals("Administrador")){
                    Admin ad = new Admin();
                    ad.setVisible(true);
                    ingresarBool = false;
                    dispose();
                }
                else if(u.getTipoArea().equals("Financiero")){
                    userLogin = u.getCodigo();
                    BSC bsc1 = new BSC(userLogin);
                    bsc1.setVisible(true);
                    ingresarBool = false;
                    dispose();
                }
                else if(u.getTipoArea().equals("Cliente")){
                    userLogin = u.getCodigo();
                    BSC bsc2 = new BSC(userLogin);
                    bsc2.setVisible(true);
                    ingresarBool = false;
                    dispose();
                }
                else if(u.getTipoArea().equals("Aprendizaje y Crecimiento")){
                    userLogin = u.getCodigo();
                    BSC bsc3 = new BSC(userLogin);
                    bsc3.setVisible(true);
                    dispose();
                }
                else if(u.getTipoArea().equals("Procesos Internos")){
                    userLogin = u.getCodigo();
                    BSC bsc4 = new BSC(userLogin);
                    bsc4.setVisible(true);
                    ingresarBool = false;
                    dispose();
                }
            }
        }
        if(ingresarBool){
                JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrecto");
                userText.setText("");
                passwordText.setText("");
            }

    }//GEN-LAST:event_ingresarLActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresarL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton salir;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
